# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: grafana-pv
#   labels:
#     release: "stable"  # 为了让后续的pvc绑定到此pv上，所以加了labels
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   volumeMode: Filesystem
#   storageClassName: local-storage
#   local: 
#     path: /home/ubuntu/grafana_data  # 本地存放目录
#   nodeAffinity:   # 调度选择
#     required: 
#       nodeSelectorTerms: 
#       - matchExpressions: 
#         - key: kubernetes.io/hostname 
#           operator: In 
#           values: 
#           - 10.176.14.41

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-pvc
#   namespace: monitoring
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: local-storage
#   selector:
#     matchLabels:
#       release: "stable" # 为了于上面的pvc绑定

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: local
    name: grafana-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/grafana_data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: grafana-volume